### PR TITLE
refactors deploy activation out of upload hook

### PR DESCRIPTION
**Pull request by cspanring**
Implements activation hook as outlined in #3 

The plugin will now only upload the packaged fastboot deploy archive, but not write to `fastboot-deploy-info.json`, which would trigger a re-deploy of the fastboot app, if the `activate` flag is not set. If the `activate` flag is set, it will upload and update the `fastboot-deploy-info.json`.

Using `ember deploy:activate --revision=myRevision` will update `fastboot-deploy-info.json` with 'myRevision' and not upload the fastboot deploy archive.

I had to move a few things around in order to get this working, biggest change: it seems I can't rely on the `distDir` config option during activation. `distDir` is used by the existing methods to compose the deployed archive's file name. As workaround I replaced the use if `distDir` with `DEFAULT_DEPLOY_ARCHIVE`, and renamed it from `dist-deploy` to `fastboot-deploy`, to be consistent with the `fastboot-deploy-info` naming schema.

Unit tests were updated to reflect the made changes and roughly cover the activation hook.

@he9qi please let me know what you think. Next steps would be to implement the revision list hooks.

### CODE REVIEW

**Comment by he9qi** [comment]
This is all good! 👍

**Comment by cspanring** [comment]
Great! Do you want to merge it and cut a new release?

**Comment by he9qi** [comment]
Will do! :)

**Comment by cspanring** [comment]
@he9qi I did not realize that `deploy-dist`, which I replaced with `fastboot-deploy`, is somewhat of a convention driven by the fastboot app server. should we rename `fastboot-deploy` to `deploy-dist`?

**Comment by he9qi** [comment]
Right, let's change back to `deploy-dist` just to follow the convention. Would you update and send pull request again?

**Comment by cspanring** [comment]
see #5

**Pull request merged**
