### PR TITLE
Test updates

### PR DESCRIPTION
**Pull request by jeffjewiss**
This ensures that the node tests are run and that tests are run against Node 4, 6, 7 and 8. I've also updated the dependencies, and setup `ember-try` to use yarn.

### CODE REVIEW

**Comment by jeffjewiss** [comment]
@he9qi here are the test changes I was talking about.

I referenced some other `ember-cli-deploy` plugins and from what I can gather there isn't much use in running `ember test` since a deploy addon doesn't provide any frontend resources and works entirely in Node. With this in mind I removed many of the dev dependencies since they aren't required and test against more versions of Node. I uncovered a promise related bug in the tests in the process.

I've tested these changes against my own site, which is using this addon.

Please let me know if you have any questions.

Cheers!

**Comment by he9qi** [comment]
@jeffjewiss Looks great! Really glad you made the upgrade 💯 .

**Comment by jeffjewiss** [comment]
Thanks for merging @he9qi! Let me know if you'd like some help maintaining the addon. I'm interesting in helping out further if you don't mind adding me to the repo. Cheers!

**Comment by he9qi** [comment]
@jeffjewiss no problem at all! 

That’ll be great! Let me add you! Thank you for contributing! 🙂

**Pull request merged**
